defaults:
  - hydra: hydra_simple
  - _self_


name: CookingZoo
separate_controllers: false

logger:
  load_dir: ${name}
  log_grad: false
  project: DiversityGeneration
  entity: gingerninja
  logger_period: 0.1
  save_model: true
  save_model_period: 5

# # Data collection-related parameters
env:
  #name: cookingZooEnv-v0
  #Other possible env names: MARL-CooperativeReaching-5-50-blinded-asymmetric-v0, MARL-CooperativeReaching-5-50-blinded-v0, matrix-game-no-state-v0
  name: matrix-game-no-state-v0
  parallel:
    sp_collection: 10
    xp_collection: 30
    eval: 6

run:
  use_cuda: false
  num_timesteps: 12000000
  num_eval_episodes: 1
  seed: 0
  eval_seed: 500
  total_checkpoints: 50
  load_from_checkpoint: -1
  device_id: 2

populations:
  num_populations: 2

train:
  timesteps_per_update: 4
  gamma: 0.99
  gamma_act_jsd: 0.1
  target_update_rate: 1e-3
  lr: 1e-3
  max_grad_norm: 1.0
  lagrange_lr: 0.05
  tolerance_factor: 0.25
  # Set to false for LIPO and BRDiv
  with_lagrange: true
  init_lagrange: 0.0
  lagrange_update_period: 10
  epochs_per_update: 10
  eps_clip: 0.2
  dual_clip: 3.0
  anneal_end: 0.5
  with_dual_clip: false
  # Set to True for LIPO.
  with_lipo: false

loss_weights:
  scale_length: 0.5
  xp_val_loss_weight: 1.0
  sp_val_loss_weight: 1.0
  jsd_weight: 0.0
  xp_loss_weights: 1.0
  entropy_regularizer_loss: 0.001
  lagrange_weights: 1.0
  final_entropy_regularizer_loss: 0.001
  anneal_end: 0.5

model:
  actor_dims:
    - 32
    - 32
  critic_dims:
    - 32
    - 32

any_play:
  with_any_play: false
  any_play_classifier_loss_weight: 1.0
  any_play_lambda: 0.001
  classifier_dims:
    - 256
    - 256

